config/routes.rb
Viralist::Application.routes.draw do
  
  root 'dashboard#index'
  resources :sessions, :only => [:new, :create, :destroy]
  get 'login', to: 'sessions#new' 
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'search', to: 'visits#search'

  resources :users

  resources :contacts

  resources :companies

  resources :stores

  resources :visits

end

app/models/visit.rb
class Visit < ActiveRecord::Base
	
	belongs_to :store
	belongs_to :user

	validates :visitdate, presence: true
	

	def days_since
		DateTime.now.mjd - visitdate.mjd
	end

	def to_s
		"#{visitdate}, #{store}"
	end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]
  before_filter :login_check

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all(:order => "created_at DESC")
  end

  def search 
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    
  end

  # GET /visits/new
  def new
    @users = User.all
    @stores = Store.all
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    
    @visit = Visit.new(visit_params)

    print @stores
    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @visit }
      else
        format.html { render action: 'new' }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:visitdate, :note, :user_id, :store_id)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :visitdate %><br>
    <%= f.date_select :visitdate, :end_year => Time.now.year, :order => [:day, :month, :year] %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <% if @visit.new_record? %>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.select :user_id, options_from_collection_for_select(@users, :id, :to_s, selected: current_user.id)%>
  </div>
  
  <div class="field">
    <%= f.label :store %><br>
    <%= f.select :store_id, options_from_collection_for_select(@stores, :id, :to_s, selected: 0)%>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit class: "btn btn-default"%>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit  , class: "btn btn-default" %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Store</th>
      <th>Visitor</th>
      <th>Days since</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= link_to visit.visitdate.strftime("%d.%m.%Y, %A"), visit, "data-no-turbolink" => true %></td>
        <td><%= link_to visit.store.to_s, visit.store, "data-no-turbolink" => true %></td>
        <td><%= link_to visit.user.to_s, visit.user %></td>
        <td><%= visit.days_since %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit), class: "btn btn-xs btn-primary" %></td>
        <td><%= link_to 'Destroy', visit, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit', new_visit_path, class: "btn btn-md btn-success"  %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

app/views/visits/search.html.erb
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.min.js"></script>
<script>
    function VisitsController($scope, $http) {
        $http.get('visits.json').success( function(data, status, headers, config) {
            $scope.visits = data;
        });

        $scope.order = '-visitdate';

        $scope.searchText = '';
    }

    </script>
<h1>Searching visits</h1>

	

<div data-ng-app="" ng-controller="VisitsController">
    
    <input ng-model="searchText">

    <div>

      <table class="table table-hover">
        <thead>
        <th> Date </th>
        <th> Store </th>
        <th> Visitor </th>
        <th> Days since </th>
        
        </thead>
        <tr ng-repeat="visit in visits| orderBy:order | filter:searchText ">
            <td><a ng-href="/visits/{{visit.id}}" data-no-turbolink>{{visit.visitdate | date:'dd.MM.yyyy, EEEE'}}</a></td>
            <td><a ng-href="/stores/{{visit.store.id}}"data-no-turbolink>{{visit.store.name}}</a></td>
            <td><a ng-href="/users/{{visit.user.id}}">{{visit.user.name}}</a></td>
            <td>{{visit.days.since}}</td>

        </tr>
      </table>


<%= link_to 'New Visit', new_visit_path, class: "btn btn-md btn-success"  %>


  </div>

app/views/visits/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js"></script>
<style type="text/css">

#mapCanvas label { width: auto; display:inline; }
#mapCanvas img { max-width: none; }
.gm-style img { max-width: none; }
.gm-style label { width: auto; display: inline; }
</style>



<div class="row" data-ng-app="">
    <div class="col-md-6">
    	<p>
  <h1>Visitation date:</h1>
  <%= @visit.visitdate %>, <%= "#{@visit.days_since} " "#{"day".pluralize(@visit.days_since)}" "#{" ago"}"%>
</p>


<p>
  <h4>By user:</h4>
  <%= @visit.user.to_s %>
</p>



<p>
  <h4>Store:</h4>
  <%= @visit.store.to_s %>
  
</p>

<p>
  <h4>Note:</h4>
  <%= @visit.note.empty? ? "No note set!" : @visit.note %>
</p>

<%= link_to 'Edit', edit_visit_path(@visit)  , class: "btn btn-default" %>



    </div>
    <div class="col-md-6">
      <div style='width: 100%; height:100%'>
        <div id="map" style='width: 100%; height: 630px;'></div>
      </div>
    </div>
  </div>




<script type="text/javascript">
var handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @visit.store.latitude %>,
      "lng": <%= @visit.store.longitude %>
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(14);
});</script>