config/routes.rb
Viralist::Application.routes.draw do
  
  root 'dashboard#index'
  resources :sessions, :only => [:new, :create, :destroy]
  get 'login', to: 'sessions#new' 
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'search', to: 'visits#search'

  resources :users

  resources :contacts

  resources :companies

  resources :stores

  resources :visits

end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :visits, dependent: :destroy
	belongs_to :contact
	belongs_to :company
	has_many :contacts
	

	validates_uniqueness_of :name, :scope => :company_id, message: "already exists within company!"
	validates :name, :city, :address, :zip, presence: true
	validates :zip, :numericality => {:only_integer => true}, length: { in: 00000..99999 } #only finnish zips

	geocoded_by :full_street_address   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates


	def last_visited
		latest = visits.where(store_id: id).order(:visitdate).reverse_order.first
		if latest.nil?
			return -1
		else
			return latest.days_since
		end
	end

	def threshold_exceeded
		return last_visited > threshold
	end

	def nearing_threshold
		return last_visited > threshold / 2
	end

	def to_s
		"#{company.name} #{name}"
	end

	def full_street_address
		"#{address}, #{zip} #{city}"
	end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_filter :login_check

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @contacts = Contact.all
    @companies = Company.all
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        @contacts = Contact.all
        @companies = Company.all
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :company_id, :address, :zip, :city, :contact_id, :threshold)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if @store.new_record? %>
      <%= f.label :company %><br>
      <%= f.select :company_id, options_from_collection_for_select(@companies, :id, :name, selected: @store.id) %><br><br>
    <% else %>

      <%= f.label :company %><br>
      <%= @store.company  %><br><br>
    <% end %>


    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <% if not @store.new_record?%>
  <div class="field">
    <%= f.label "Primary contact" %><br>
    <%= f.select :contact_id, options_from_collection_for_select(@store.contacts, :id, :to_s, selected: @store.id) %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>


  <div class="field">
    <%= f.label :threshold %><br>
    <%= f.text_field :threshold, :value => @store.new_record? ? 30 : @store.threshold %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-md btn-primary"%>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store , class: "btn btn-default" %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Contact</th>
      <th>Threshold</th>
      <th>Total visits</th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store, store, "data-no-turbolink" => true %></td>
        <td><%= store.full_street_address %></td>
        <td><%= store.contact %></td>
        <td><%= store.threshold %></td>
        <td><%= store.visits.count %></td>
        <td><%= link_to 'Edit', edit_store_path(store), class: "btn btn-xs btn-primary" %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path, class: "btn btn-success"%>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

app/views/stores/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js"></script>
<style type="text/css">

#mapCanvas label { width: auto; display:inline; }
#mapCanvas img { max-width: none; }
.gm-style img { max-width: none; }
.gm-style label { width: auto; display: inline; }
</style>







<div class="row" data-ng-app="">
    <div class="col-md-6">


<p>
  <h3><%= "#{@store}, " "#{@store.company}"  %></h3>
</p>
<br>
<p>
  <h4>Address:</h4>
  <%= @store.full_street_address %>
</p>
<p>
  <h4>Threshold:</h4>
  <%= @store.threshold %>
</p>
<p>
  <h4>Last visited:</h4>
  <%= @store.visits.empty? ? "No visitations yet" : " #{@store.last_visited} #{"day".pluralize(@store.last_visited)} ago"%>

</p>
<p>
<% if @store.contact.nil? %>
  <h4>No primary contact set</h4>
  <% else %>
  <h4>Primary contact</h4>
  <%= link_to @store.contact, @store.contact%>
<% end %>

  
   
   
</p>

<% if @store.contacts.empty? %>
  <h4>No contacts yet!</h4><br><br>
<% else %>
  <h4>All contacts</h4>
<ul class="list-group" style="width:20%">
  <% @store.contacts.each do |contact| %>
  <li class="list-group-item"><%= link_to contact, contact_path(contact.id) %></li>
<% end %>
<% end %>

</ul>


<%= link_to 'Edit', edit_store_path(@store), class: "btn btn-default" %>

</div>
    <div class="col-md-6">
      <div style='width: 100%; height:100%'>
        <div id="map" style='width: 100%; height: 620px;'></div>
      </div>
    </div>
  </div>




<script type="text/javascript">
var handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @store.latitude %>,
      "lng": <%= @store.longitude %>
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(14);
});</script>