config/routes.rb
Viralist::Application.routes.draw do
  
  root 'dashboard#index'
  resources :sessions, :only => [:new, :create, :destroy]
  get 'login', to: 'sessions#new' 
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'search', to: 'visits#search'

  resources :users

  resources :contacts

  resources :companies

  resources :stores

  resources :visits

end

app/models/company.rb
class Company < ActiveRecord::Base
	
	belongs_to :contact
	has_many :contacts
	has_many :stores

	def to_s
		"#{name}"
	end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_filter :login_check

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :contact_id)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br>
    <%= f.select :contact_id, options_from_collection_for_select(@company.contacts, :id, :to_s, selected: 0) %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-md btn-primary" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company  , class: "btn btn-default" %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of stores</th>
      <th>Contact</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company %></td>
        <td><%= company.stores.count %></td>
        <td><%= link_to company.contact.to_s, company.contact %></td>
        <td><%= link_to 'Edit', edit_company_path(company), class: "btn btn-xs btn-primary"%></td>
        <td><%= link_to 'Destroy', company, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path, class: "btn btn-md btn-success" %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<div class="row">
	<div class="col-md-6">

<p>
  <h1><%= @company.name %></h1>
  
</p>

<p>
  <h3><%= @company.contact.nil? ? "No primary contact set" : "Primary contact" %></h3>
  <%= link_to @company.contact.to_s, @company.contact %>
</p>

<% if @company.contacts.empty? %>
	<strong>No contacts yet!</strong><br><br>
<% else %>
	<strong>All contacts</strong>
<ul class="list-group" style="width:20%">
	<% @company.contacts.each do |contact| %>
	<li class="list-group-item"><%= link_to contact, contact_path(contact.id) %></li>
<% end %>
<% end %>

</ul>


<%= link_to 'Edit', edit_company_path(@company)  , class: "btn btn-default" %> 


	</div><br>
	<div class="col-md-6">
<% if @company.stores.empty? %>
		<strong>No stores yet!</strong>
<% else %>
	<strong>Stores:</strong>
	<ul class="list-group" >
	<% @company.stores.each do |store| %>
	<li class="list-group-item"><%=  link_to "#{store}", store, "data-no-turbolink" => true %></li>
	<% end %>
<% end %>
<br>
	</div>
</div>