config/routes.rb
Viralist::Application.routes.draw do
  
  root 'dashboard#index'
  resources :sessions, :only => [:new, :create, :destroy]
  get 'login', to: 'sessions#new' 
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'search', to: 'visits#search'

  resources :users

  resources :contacts

  resources :companies

  resources :stores

  resources :visits

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'dashboard', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to "visits", visits_path %></li>
<li><%= link_to "search", search_path %></li>
<li><%= link_to "contacts", contacts_path %></li>
<li><%= link_to "companies", companies_path %></li>
<li><%= link_to "stores", stores_path %></li>
<li><%= link_to "users", users_path %></li>

<!--separator-->
<li style="
            display:inline-block;
            padding: 10px;
            width: 114px;
            margin: 0;">&nbsp;</li>

<% if not current_user.nil?  %>
	<li><%= link_to current_user.realname, user_path(current_user) %></li>
	<li><%= link_to "logout", logout_path, method: :delete %></li>
<% else %>
	<li><%= link_to "login", login_path %></li>
	<li><%= link_to "signup", signup_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Viralist" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Viralist" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>  
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>